[Settings]
ID = 'readmo.de'

[build]
command = 'npm run build'
publish = 'build'

# Redirect default Netlify subdomain to primary domain
[[redirects]]
from="/*"
to="https://readermo.de/:splat"
status=301
